### ISSUE TITLE
Issue to submit the taskchain for wmLHE + GEN-SIM + DIGI-RECO

### ISSUE THREAD

**Issue by srimanob** [cms-PdmV/cmsPdmV#731]
I can't submit the taskchain from the ROOT request,

https://cms-pdmv-int.cern.ch/mcm/requests?prepid=SMP-Summer12WMLHE-00011&page=0&shown=127

From what I did, 
https://cms-pdmv-int.cern.ch/mcm/chained_requests?contains=SMP-Summer12WMLHE-00011&page=0&shown=15

I disable "SMP-chain_Summer12WMLHE_flowLHE2S12-00003", since we don't need it, I think. I only want to submit using "SMP-chain_Summer12WMLHE_flowLHE2S12_flowS12to53GenValidation-00009"

The validation of the latter chain request went well, I move all samples to "approve" status. When I click "submit" from the ROOT request, it shows that the submission fails.

Could you please check?

**Comment by srimanob** [comment]
From the notification email:

We have a commandline.
Campaign and request-id are not set. Provide at least the Campaign.
Re-encoding for nested dicts
Re-encoding for nested dicts


Error: 
Traceback (most recent call last):
 File "/afs/cern.ch/cms/PPD/PdmV/tools/wmcontrol/wmcontrol.py", line 1103, in <module>
   loop_and_submit(config)
 File "/afs/cern.ch/cms/PPD/PdmV/tools/wmcontrol/wmcontrol.py", line 498, in loop_and_submit
   workflow = wma.makeRequest(wma.WMAGENT_URL,params,encodeDict=(service_params['request_type']=='TaskChain'))
 File "/afs/cern.ch/cms/PPD/PdmV/tools/wmcontrol/modules/wma.py", line 146, in makeRequest
   conn.request("POST",  "/reqmgr/create/makeSchema", encodedParams, headers)
 File "/afs/cern.ch/cms/slc6_amd64_gcc472/external/python/2.6.4/lib/python2.6/httplib.py", line 898, in request
   self._send_request(method, url, body, headers)
 File "/afs/cern.ch/cms/slc6_amd64_gcc472/external/python/2.6.4/lib/python2.6/httplib.py", line 935, in _send_request
   self.endheaders()
 File "/afs/cern.ch/cms/slc6_amd64_gcc472/external/python/2.6.4/lib/python2.6/httplib.py", line 892, in endheaders
   self._send_output()
 File "/afs/cern.ch/cms/slc6_amd64_gcc472/external/python/2.6.4/lib/python2.6/httplib.py", line 764, in _send_output
   self.send(msg)
 File "/afs/cern.ch/cms/slc6_amd64_gcc472/external/python/2.6.4/lib/python2.6/httplib.py", line 723, in send
   self.connect()
 File "/afs/cern.ch/cms/slc6_amd64_gcc472/external/python/2.6.4/lib/python2.6/httplib.py", line 1100, in connect
   self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
 File "/afs/cern.ch/cms/slc6_amd64_gcc472/external/python/2.6.4/lib/python2.6/ssl.py", line 350, in wrap_socket
   suppress_ragged_eofs=suppress_ragged_eofs)
 File "/afs/cern.ch/cms/slc6_amd64_gcc472/external/python/2.6.4/lib/python2.6/ssl.py", line 118, in __init__
   self.do_handshake()
 File "/afs/cern.ch/cms/slc6_amd64_gcc472/external/python/2.6.4/lib/python2.6/ssl.py", line 293, in do_handshake
   self._sslobj.do_handshake()
ssl.SSLError: [Errno 1] _ssl.c:480: error:14094415:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate expired

**Comment by anorkus** [comment]
fixed in https://github.com/cms-PdmV/cmsPdmV/commit/6326241bcade06654f8be6b1810196caf70728bf
