### ISSUE TITLE
Error getting requests with script

### ISSUE THREAD

**Issue by davidsheffield** [cms-PdmV/cmsPdmV#788]
In the past couple of months, I started encountering errors when I tried to use the get method with the rest.py script. My code is in https://github.com/davidsheffield/McMScripts/blob/master/manageRequests.py#L312-L349, the relevant parts of which do:

```
sys.path.append('/afs/cern.ch/cms/PPD/PdmV/tools/McM/')
from rest import *
mcm = restful( dev=False )
mcm.getA('requests', query="dataset_name=ZprimeToZhToZhadhtata_narrow_M-4500_13TeV-madgraph&member_of_campaign=RunIIWinter15GS")
```

This will sometimes result in the error

```
ERROR
Traceback (most recent call last):
  File "/afs/cern.ch/cms/PPD/PdmV/tools/McM/rest.py", line 71, in get
    d=json.loads(self.response())
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.6/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.6/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.6/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>500 Internal Server Error</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>500 Internal Server Error</h2>
        <p>The server encountered an unexpected condition which prevented it from fulfilling the request.</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/CherryPy-3.2.4-py2.6.egg/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.6/site-packages/CherryPy-3.2.4-py2.6.egg/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/CherryPy-3.2.4-py2.6.egg/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/mcm/cmsPdmV/mcm/rest_api/RestAPIMethod.py", line 66, in default
    return method(*vpath, **params)
  File "/home/mcm/cmsPdmV/mcm/rest_api/ControlActions.py", line 161, in GET
    res = self.search(args, db_name=db_name, page=page, limit=limit, get_raw=get_raw)
  File "/home/mcm/cmsPdmV/mcm/rest_api/ControlActions.py", line 170, in search
    res = odb.full_text_search("search", lucene_query, page=page, limit=limit, get_raw=get_raw)
  File "/home/mcm/cmsPdmV/mcm/couchdb_layer/mcm_database.py", line 520, in full_text_search
    'include_docs': True, 'skip': skip, 'sort': '_id'}, get_raw=get_raw) #we sort ascending by doc._id field
  File "/home/mcm/cmsPdmV/mcm/couchdb_layer/couchDB_interface.py", line 135, in FtiSearch
    data = self.opener.open(db_request)
  File "/usr/lib64/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib64/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.6/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: Internal Server Error
</pre>
    <div id="powered_by">
    <span>Powered by <a href="http://www.cherrypy.org">CherryPy 3.2.4</a></span>
    </div>
    </body>
</html>
```

I changed my code to retry a few times if this happens, which will usually eventually get me the request. But is there any way to stop this error? I only started noticing it over the last few months.

**Comment by anorkus** [comment]
Hi,

i would bet that couchDB connection time_out/crashed. My bet that in your script you dont use time.sleep() between your queries to mcm ;)

**Comment by davidsheffield** [comment]
I'll give that a try. Thanks.
