### ISSUE TITLE
GEN request with different cmsDriver can't go to validation (with/without process string, both cases)

### ISSUE THREAD

**Issue by srimanob** [cms-PdmV/cmsPdmV#802]
- With process string:
Traceback (most recent call last): File "/home/mcm/cmsPdmV/mcm/rest_api/RequestActions.py", line 804, in approve _res = req.approve(val) File "/home/mcm/cmsPdmV/mcm/json_layer/json_base.py", line 259, in approve __ret = getattr(self, fcn)() File "/home/mcm/cmsPdmV/mcm/json_layer/request.py", line 298, in ok_to_move_to_approval_validation __query['process_string'] = self.get_attribute('process_string') TypeError: 'str' object does not support item assignment

- Without process string:
It is illegale to approve validation in status new. The sequences of the request has been changed with respect to the campaign, but no processing string has been provided

**Comment by anorkus** [comment]
fixed in https://github.com/cms-PdmV/cmsPdmV/commit/0e1140312cdd0ddf6aa8bae7c403ae38bf75a1fc
