### ISSUE TITLE
invalidation acknowledgement not functioning

### ISSUE THREAD

**Issue by vlimant** [cms-PdmV/cmsPdmV#886]
calls to 
 /restapi/invalidations/acknowledge/QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8RunIIFall17MiniAOD-NoPU_94X_mc2017_realistic_v10-v2MINIAODSIM

 result in 

ERROR
Traceback (most recent call last):
  File "/data/unified/WmAgentScripts/Unified/McMClient.py", line 73, in get
    d=json.loads(self.response())
  File "/data/srv/wmagent/v1.1.0.patch2/sw/slc6_amd64_gcc493/external/python/2.7.11-comp/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/data/srv/wmagent/v1.1.0.patch2/sw/slc6_amd64_gcc493/external/python/2.7.11-comp/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/srv/wmagent/v1.1.0.patch2/sw/slc6_amd64_gcc493/external/python/2.7.11-comp/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>

similarly a call to

/restapi/invalidations/acknowledge/pdmvserv_task_BTV-RunIIFall17DRPremix-00040__v1_T_171121_175900_2154

gives back

ERROR
Traceback (most recent call last):
  File "/data/unified/WmAgentScripts/Unified/McMClient.py", line 73, in get
    d=json.loads(self.response())
  File "/data/srv/wmagent/v1.1.0.patch2/sw/slc6_amd64_gcc493/external/python/2.7.11-comp/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/data/srv/wmagent/v1.1.0.patch2/sw/slc6_amd64_gcc493/external/python/2.7.11-comp/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/srv/wmagent/v1.1.0.patch2/sw/slc6_amd64_gcc493/external/python/2.7.11-comp/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>

which prevents the acknowledgement of the invalidation

**Comment by anorkus** [comment]
your actual url is:
https://cms-pdmv.cern.ch/mcm//restapi/invalidations/acknowledge/pdmvserv_task_BTV-RunIIFall17DRPremix-00040__v1_T_171121_175900_2154

same with: 
https://cms-pdmv.cern.ch/mcm//restapi/batches/notify

double slash makes new framework return 404 as such url doesn't exist.
